### ISSUE TITLE
Extra tensors find in CPU while generating adversarial samples

### ISSUE THREAD

**Issue by Liuhm0710** [luckybird1994/ASAM#6]
[580] SAM-1B/sa_000000/sa_16.jpg does not exist!
[581] SAM-1B/sa_000000/sa_17.jpg does not exist!
[582] a person is sitting on a bench in front of a building
[583] init: torch.Size([1, 4, 64, 64])
[584] Traceback (most recent call last):
[585]   File "grad_null_text_inversion_edit.py", line 937, in <module>
[586]     image_inv, x_t, worst_mask, vis, worst_iou = text2image_ldm_stable_last(ldm_stable, [prompt], controller, latent=x_t, num_inference_steps=NUM_DDIM_STEPS, guidance_scale=GUIDANCE_SCALE, generator=None, uncond_embeddings=uncond_embeddings, mask_control=control_mask,raw_img=raw_img,boxes=boxes, label_masks_256=label_masks_256)    
[587]   File "/root/anaconda3/envs/ASAM/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
[588]     return func(*args, **kwargs)
[589]   File "grad_null_text_inversion_edit.py", line 701, in text2image_ldm_stable_last
[590]     loss_ce = args.gamma * torch.nn.functional.binary_cross_entropy_with_logits(ad_low_res_logits, label_masks_256/255.0) 
[591]   File "/root/anaconda3/envs/ASAM/lib/python3.8/site-packages/torch/nn/functional.py", line 3150, in binary_cross_entropy_with_logits
[592]     return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)
[593] RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

I find that 5 tensors were set to CPU at the beginning, while doing this 
scheduler = DDIMScheduler(beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", clip_sample=False, set_alpha_to_one=False)

But i havent figured it out how to move it to GPU. Sorry to bother you.

**Comment by hkxiao** [comment]
You can try to cancel  `ldm_stable.disable_xformers_memory_efficient_attention()` . Here is the skip link:
https://github.com/luckybird1994/ASAM/blob/bf478e3210659c9b98c213af583176d1037943ab/grad_null_text_inversion_edit.py#L805 Good Luck!

**Comment by Liuhm0710** [comment]
# Load Stable Diffusion & ControlNet
    device = torch.device('cuda:0') if torch.cuda.is_available() else torch.device('cpu')
    scheduler = DDIMScheduler(beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", clip_sample=False, set_alpha_to_one=False)
    check_tensors_on_cpu()
    MY_TOKEN = "your huggingface token"
    LOW_RESOURCE = False 
    NUM_DDIM_STEPS = args.ddim_steps
    GUIDANCE_SCALE = args.guidance_scale
    MAX_NUM_WORDS = 77
    controlnet = ControlNetModel.from_single_file(args.controlnet_path).to(device)    
    ldm_stable = StableDiffusionControlNetPipeline.from_pretrained("stable-diffusion-v1-5",controlnet=controlnet, scheduler=scheduler).to(device)

    # try:
    #     ldm_stable.disable_xformers_memory_efficient_attention()
    # except AttributeError:
    #     print("Attribute disable_xformers_memory_efficient_attention() is missing")    

I have cancelled the code but it still has the problem beyond.check_tensors_on_cpu() is the code to check whether there are tensors on CPU.

**Comment by Liuhm0710** [comment]
The function is written below:
def check_tensors_on_cpu():

    gc.collect()


    objects = gc.get_objects()


    cpu_tensors = [obj for obj in objects if isinstance(obj, torch.Tensor) and obj.is_cuda == False]

    if cpu_tensors:
        print(f"CPU has {len(cpu_tensors)} tensors allocated on it.")
        for tensor in cpu_tensors:
            print(f"Tensor on CPU: {tensor}, shape: {tensor.shape}")
    else:
        print("CPU has no tensors allocated on it.")


And when I run the code, its output is 
[4] Namespace(alpha=0.02, beta=1.0, caption_path='SAM-1B/sa_000000-blip2-caption.json', check_controlnet=False, check_inversion=False, control_mask_dir='SAM-1B/sa_000000', controlnet_path='ckpt/control_v11p_sd15_mask_adv.pth', data_root='SAM-1B/sa_000000', ddim_steps=50, debug=False, end=11186, eps=0.2, gamma=100.0, guess_mode=False, guidance_scale=7.5, inversion_dir='output/sa_000000-Inversion/embeddings', kappa=100.0, model='sam', model_pth='ckpt/sam_vit_b_01ec64.pth', model_type='vit_b', mu=0.5, norm=2, prefix='skip-ablation-01-mi', random_latent=False, sam_batch=140, save_root='output/sa_000000-Grad', seed=0, start=0, steps=10)
[5] ==> Preparing Model..
[6] CPU has 5 tensors allocated on it.
[7] Tensor on CPU: tensor([0.0008, 0.0009, 0.0009, 0.0009, 0.0009, 0.0009, 0.0009, 0.0009, 0.0009,
[8]         0.0009, 0.0009, 0.0009, 0.0009, 0.0009, 0.0009, 0.0009, 0.0009, 0.0009,

the below is the exact tensor and its shape is 1000.

**Comment by hkxiao** [comment]
Please wait for a moment, I will check this bug as soon.

**Comment by hkxiao** [comment]
I run my released code again and don‘t meet the same question as you. Can you provide the environment and file structure? Or I update the `environment.yaml` from the local, thus you can check if the environment is the same. Gook Luck!

**Comment by Liuhm0710** [comment]
Sorry for not reply so far. I made a mistake while checking the problems. The tensor created by scheduler did not affect the problem I made. And after I checked again, I found that the tensor on CPU was created during the process on line 654: 
          if args.model == 'sam':
                example = {}
                example['image'] = image_m[0]*255.0
                example['boxes'] = boxes
                example['original_size'] = image_size
                output, interbeddings = net([example], multimask_output=False)
                output = output[0]
                ad_masks, ad_iou_predictions, ad_low_res_logits = output['masks'],output['iou_predictions'],output['low_res_logits']  

The exact reason is that net failed to recognize masks on the offered examples, so example['boxes'] turned out to be null, and was set to CPU. My idea is to skip the examples whose mask is null. (But i havent made it yet because i'm dealing another task now)

By the way, I used the dataset you offered, but it still has some problems on first step and second, maybe you can check and fix it.

**Comment by hkxiao** [comment]
Thanks for your careful checking! We will check the released data soon!

Liuhm0710 ***@***.***> 于2024年7月28日周日 15:48写道：
